# Generated by Django 4.2.7 on 2023-11-24 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(default='1234', max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.IntegerField(unique=True)),
                ('profile_photo_url', models.URLField()),
                ('role', models.CharField(default='faculty', max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('aadhar', models.CharField(blank=True, max_length=12, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(default='1234', max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('admission_date', models.DateField(auto_now_add=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aadhar', models.CharField(blank=True, max_length=12, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.IntegerField(unique=True)),
                ('profile_photo_url', models.URLField()),
                ('role', models.CharField(default='student', max_length=100)),
                ('Branch', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('semester', models.IntegerField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=None, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_present', models.BooleanField(default=None)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='login.subjects')),
            ],
        ),
    ]
