# Generated by Django 4.2.7 on 2023-11-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_attendance_student_id_attendance_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_id',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
