# Generated by Django 4.2.7 on 2023-11-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_attendance_student_attendance_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
