# Generated by Django 4.2.7 on 2023-11-25 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_attendance_is_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='staff',
        ),
    ]
