# Generated by Django 4.2.7 on 2023-11-25 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_subjects_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='classassigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('subject_code', models.CharField(blank=True, max_length=20, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classassigned', to='login.faculty')),
            ],
        ),
    ]
