# Generated by Django 4.2.7 on 2023-11-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_classassigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student_id',
            field=models.IntegerField(default=None),
        ),
    ]
